name: client_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.0.0  # Enables file selection from laptop (web-friendly)
  shared_preferences: ^2.2.2 
  razorpay_flutter: ^1.3.4  
  image_picker: ^1.0.4 
  supabase_flutter: ^1.0.0  # Use the latest version
  lottie: ^2.6.0
  animated_text_kit: ^4.2.2
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
