name: client_web
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.1.2  # Enables file selection from laptop (web-friendly)
  shared_preferences: ^2.2.2 
  image_picker: ^1.0.4 
  supabase_flutter: ^2.8.4
  lottie: ^3.3.1
  animated_text_kit: ^4.2.2
  audioplayers: ^6.4.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_credit_card: ^4.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
