name: freelancer_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  cached_network_image: ^3.4.1
  fl_chart: ^0.70.2
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.0.4  
  pdf: ^3.11.3
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.8.3 # Ensure it's the latest version
  timeago: ^3.7.0
  universal_html: ^2.2.4
  lottie: ^3.3.1
  animated_text_kit: ^4.2.2
  audioplayers: ^6.4.0
# Check for the latest version on pub.dev


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
